"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['blackBishop.png','blackKing.png', 'blackRook.png', 'blackQueen.png', 'blackKnight.png', 'whiteQueen.png', 'whiteKing.png', 'whiteRook.png', 'whiteBishop.png', 'whiteKnight.png', 'blackPawn.png', 'whitePawn.png']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
